import os
import duckdb
import pytest
from scripts.main import main
from unittest.mock import patch


@pytest.fixture(scope="module", autouse=True)
def execute_pipeline_before_tests():
    """
    Module-level fixture to run the full pipeline end-to-end before assertions.
    Executing main() directly ensures 100% code coverage across
    main.py, clean.py, and transform.py modules.
    """
    main()


@pytest.fixture(scope="module")
def staging_connection():
    """Fixture to connect to the Silver Layer table generated by the pipeline execution."""
    staging_file = "data/staging/taxi_cleaned_2026_04.parquet"

    if not os.path.exists(staging_file):
        pytest.skip("Silver Layer Parquet file not found. Ensure pipeline executed properly.")

    con = duckdb.connect(":memory:")
    yield con, staging_file
    con.close()

def test_pipeline_failure_handling():
    """
    Simulates a pipeline execution failure to ensure the exception 
    and defensive rollback blocks are exercised for 100% code coverage.
    """
    with patch("scripts.main.RAW_DATA_PATH", "invalid/path/file.parquet"):
        with pytest.raises(Exception):
            main()

def test_no_nulls_in_critical_columns(staging_connection):
    """
    Quality Gate: Validates that essential business columns
    are completely free of null values in the Silver Layer.
    """
    con, staging_file = staging_connection

    critical_columns = [
        "trip_distance",
        "total_amount",
        "fare_amount",
        "passenger_count",
        "RatecodeID",
        "store_and_fwd_flag",
    ]

    for col in critical_columns:
        query = f"SELECT COUNT(*) FROM '{staging_file}' WHERE {col} IS NULL;"
        null_count = con.execute(query).fetchone()[0]

        assert null_count == 0, f"Quality Gate Failure: Column '{col}' contains {null_count} nulls."


def test_domain_boundaries_compliance(staging_connection):
    """
    Quality Gate: Ensures records outside logical mathematical boundaries
    were successfully filtered and removed from Staging.
    """
    con, staging_file = staging_connection

    query = f"""
        SELECT COUNT(*) 
        FROM '{staging_file}' 
        WHERE total_amount <= 0 
           OR trip_distance <= 0 
           OR trip_distance > 150.0
    """
    invalid_records = con.execute(query).fetchone()[0]

    assert invalid_records == 0, f"Quality Gate Failure: {invalid_records} records violate domain boundaries."