import os
import duckdb
import pytest
from scripts.main import main
from unittest.mock import patch
from pathlib import Path

RAW_DATA_PATH = Path("data/raw/yellow_tripdata_2026-04.parquet")

@pytest.fixture(scope="session", autouse=True)
def setup_mock_raw_data():
    """Ensures that the data/raw folder and a minimum parquet file exist for testing."""
    RAW_DATA_PATH.parent.mkdir(parents=True, exist_ok=True)
    
    if not RAW_DATA_PATH.exists():
        # Creates a synthetic parquet file with the minimum expected structure
        con = duckdb.connect(":memory:")
        con.execute(f"""
            COPY (

                SELECT 
                    1 AS VendorID,
                    '2026-04-01 10:00:00'::TIMESTAMP AS tpep_pickup_datetime,
                    '2026-04-01 10:15:00'::TIMESTAMP AS tpep_dropoff_datetime,
                    1.0 AS passenger_count,
                    2.5 AS trip_distance,
                    1 AS RatecodeID,
                    'N' AS store_and_fwd_flag,
                    1 AS PULocationID,
                    2 AS DOLocationID,
                    1 AS payment_type,
                    15.0 AS fare_amount,
                    1.0 AS extra,
                    0.5 AS mta_tax,
                    3.0 AS tip_amount,
                    0.0 AS tolls_amount,
                    0.3 AS improvement_surcharge,
                    19.8 AS total_amount,
                    2.5 AS congestion_surcharge,
                    0.0 AS Airport_fee,
                    0.0 AS cbd_congestion_fee
            ) TO '{RAW_DATA_PATH}' (FORMAT PARQUET);
        """)
        con.close()


@pytest.fixture(scope="module", autouse=True)
def execute_pipeline_before_tests():
    """
    Module-level fixture to run the full pipeline end-to-end before assertions.
    Executing main() directly ensures 100% code coverage across
    main.py, clean.py, and transform.py modules.
    """
    main()


@pytest.fixture(scope="module")
def staging_connection():
    """Fixture to connect to the Silver Layer table generated by the pipeline execution."""
    staging_file = "data/staging/taxi_cleaned_2026_04.parquet"

    if not os.path.exists(staging_file):
        pytest.skip("Silver Layer Parquet file not found. Ensure pipeline executed properly.")

    con = duckdb.connect(":memory:")
    yield con, staging_file
    con.close()

def test_pipeline_failure_handling():
    """
    Simulates a pipeline execution failure to ensure the exception 
    and defensive rollback blocks are exercised for 100% code coverage.
    """
    with patch("scripts.main.RAW_DATA_PATH", "invalid/path/file.parquet"):
        with pytest.raises(Exception):
            main()

def test_no_nulls_in_critical_columns(staging_connection):
    """
    Quality Gate: Validates that essential business columns
    are completely free of null values in the Silver Layer.
    """
    con, staging_file = staging_connection

    critical_columns = [
        "trip_distance",
        "total_amount",
        "fare_amount",
        "passenger_count",
        "RatecodeID",
        "store_and_fwd_flag",
    ]

    for col in critical_columns:
        query = f"SELECT COUNT(*) FROM '{staging_file}' WHERE {col} IS NULL;"
        null_count = con.execute(query).fetchone()[0]

        assert null_count == 0, f"Quality Gate Failure: Column '{col}' contains {null_count} nulls."


def test_domain_boundaries_compliance(staging_connection):
    """
    Quality Gate: Ensures records outside logical mathematical boundaries
    were successfully filtered and removed from Staging.
    """
    con, staging_file = staging_connection

    query = f"""
        SELECT COUNT(*) 
        FROM '{staging_file}' 
        WHERE total_amount <= 0 
           OR trip_distance <= 0 
           OR trip_distance > 150.0
    """
    invalid_records = con.execute(query).fetchone()[0]

    assert invalid_records == 0, f"Quality Gate Failure: {invalid_records} records violate domain boundaries."